name: Setup

inputs:
  key:
    description: 'CPM cache key'
    required: true
  version:
    description: 'CPM cache version'
    required: true

runs:
  using: composite
  steps:
    - name: Install sccache
      uses: Eden-CI/sccache-action@v0.0.1
      with:
        disable_annotations: true

    - name: Download Forgejo environment
      uses: actions/download-artifact@v7.0.0
      with:
        name: forgejo-env

    - name: Load payload environment
      shell: bash
      run: |
        . ./.ci/fj/load-env.sh

    - name: Clone
      uses: actions/download-artifact@v7.0.0
      with:
        name: eden

    - name: Set up CPM cache
      uses: actions/cache@v5.0.1
      with:
        path: |
          ${{ github.workspace }}/.cache
        key: ${{ inputs.key }}-cpm-${{ inputs.version }}
