name: "Android"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true
      matrix_platform:
        description: 'matrix platform'
        type: string
        required: true

env:
  ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
  ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}

jobs:
  android:
    name: "Android"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJson(inputs.matrix_platform) }}
    env:
      TARGET: "${{ matrix.target.flavor }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-amd64-universal
          version: ${{ inputs.cpm-cache-version }}

      - name: Install dependencies
        run: |
          ./.ci/android/deps.sh

      - name: Build
        run: |
          JAVA_HOME=$JAVA_HOME_17_X64 ./.ci/android/build.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Upload APK
        uses: actions/upload-artifact@v6.0.0
        with:
          name: android-${{ matrix.target.flavor }}
          path: artifacts/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v6.0.0
        with:
          name: android-aab-${{ matrix.target.flavor }}
          path: artifacts/*.aab
