name: "AppImage"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true
      force_pgo:
        description: 'test PGO builds'
        type: string
        required: true
      matrix:
        description: 'matrix platform'
        type: string
        required: true
      compiler:
        description: 'matrix platform'
        type: string
        required: true
env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}

jobs:
  linux:
    name: "AppImage ${{ matrix.os.arch }} ${{ matrix.compiler.program }} ${{ matrix.compiler.target }}"
    runs-on: ${{ matrix.os.runs-on }}
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
      options: --privileged --device /dev/fuse

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.matrix) }}
        compiler: ${{ fromJson(inputs.compiler) }}

    env:
      TARGET: "${{ matrix.os.arch }}"
      COMPILER: "${{ matrix.compiler.program }}"
      PGO_TARGET: "${{ matrix.compiler.target }}"
      FULL_ARCH: ${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler.program }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Install dependencies
        run: |
          chmod a+x ./.ci/linux/deps.sh
          ./.ci/linux/deps.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Configure
        shell: bash
        run:  .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        shell: bash
        run: cmake --build build

      - name: Package
        shell: bash
        run: ./.ci/linux/package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: linux-${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}
          path: ./*.AppImage*
