name: Create Master Release

on:
  repository_dispatch:
    types: [master]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Parse Forgejo payload
        uses: ./.github/workflows/parse
        with:
          build-id: master

      - name: Set environment variables
        run: |
          echo "REPO=Eden-CI/Master" >> $GITHUB_ENV
          echo "DEVEL=true" >> $GITHUB_ENV

      - name: Package artifacts nicely
        run: |
          chmod a+x pack.sh
          ./pack.sh

      - name: Generate changelog
        run: |
          export FORGEJO_TOKEN=${{ secrets.FORGEJO_TOKEN }}
          export ID=${FORGEJO_REF}
          ./changelog/master.sh > changelog.md

      - name: Delete Previous Release
        run: |
          gh release delete "$FORGEJO_REF" --repo "$REPO" --cleanup-tag  -y
          sleep 5
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Eden Master - ${{ env.FORGEJO_REF }}"
          tag_name: ${{ env.FORGEJO_REF }}
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          prerelease: false
          draft: false
          generate_release_notes: false
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*
