name: Create PR Release

on:
  repository_dispatch:
    types: [pull_request]

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-id: 'pull_request'
    secrets: inherit

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Load payload environment
        shell: bash
        run: |
          ./.ci/forgejo.sh --load-payload-env

      - name: Set environment variables
        run: |
          echo "REPO=Eden-CI/PR" >> $GITHUB_ENV
          echo "DEVEL=true" >> $GITHUB_ENV

      - name: Package artifacts nicely
        run: |
          export ID=${FORGEJO_PR_NUMBER}-${FORGEJO_REF}
          ./pack.sh

      - name: Generate changelog
        run: |
          ./.ci/changelog/generate.sh pull_request > changelog.md

      - name: Delete Previous Release
        run: |
          gh release delete "$FORGEJO_PR_NUMBER" --repo "$REPO" --cleanup-tag  -y
          sleep 5
        env:
          GH_TOKEN: "${{ secrets.CUSTOM_GITHUB_TOKEN }}"
        continue-on-error: true

      - name: Release (sha)
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "${{ env.FORGEJO_TITLE }}"
          tag_name: ${{ env.FORGEJO_PR_NUMBER }}-${{ env.FORGEJO_REF }}
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*

      - name: Release (PR)
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: ${{ env.FORGEJO_TITLE }}
          tag_name: ${{ env.FORGEJO_PR_NUMBER }}
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          discussion_category_name: "PRs"
          make_latest: true
