name: "[Auto] Forgejo Pull Request"

on:
  repository_dispatch:
    types: [pull_request]

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}

jobs:
  build:
    name: Build
    concurrency:
      group: pull_request-${{ github.event.client_payload.number }}
      cancel-in-progress: true
    uses: ./.github/workflows/build.yml
    with:
      devel: true
      build-id: 'pull_request'
    secrets: inherit

  status:
    name: Forgejo Status
    needs: [build]
    if: ${{ always() }}
    uses: ./.github/workflows/status.yml
    with:
      build-id: 'pull_request'
    secrets: inherit

  release:
    name: Pull Request Release
    needs: [build]
    uses: ./.github/workflows/release.yml
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write
    with:
      devel: true
      build-id: 'pull_request'
    secrets: inherit
