name: "[Manual] Master branch test"

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    concurrency:
      group: push-build
      cancel-in-progress: false
    uses: ./.github/workflows/build.yml
    with:
      build-id: 'push'
    secrets: inherit

  release:
    name: Push Release
    needs: [build]
    uses: ./.github/workflows/release.yml
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write
    with:
      build-id: 'push'
    secrets: inherit
