name: "- Push Build Workflow"

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-id: 'push'
    secrets: inherit

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Parse Forgejo payload
        shell: bash
        run: |
          echo "${{ toJSON(github.event.client_payload) }}" > ./payload.json
          ./.ci/forgejo-ci.sh --parse push

      - name: Set environment variables
        run: |
          echo "REPO=Eden-CI/Master" >> $GITHUB_ENV
          echo "DEVEL=true" >> $GITHUB_ENV

      - name: Package artifacts nicely
        run: |
          export ID=continuous
          ./pack.sh

      - name: Generate changelog
        run: ./.ci/changelog/generate.sh push > changelog.md

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Eden Continuous Build - ${{ env.FORGEJO_REF }}"
          tag_name: continuous
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          prerelease: false
          draft: false
          generate_release_notes: false
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*
