name: Create Release

on:
  repository_dispatch:
    types: [tag]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-type: 'Release'
      devel: false
      build-id: 'tag'

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Parse Forgejo payload
        uses: ./.github/workflows/parse
        with:
          build-id: tag

      - name: Set environment variables
        run: |
          echo "REPO=eden-emulator/Releases" >> $GITHUB_ENV
          echo "DEVEL=false" >> $GITHUB_ENV

      - name: Package artifacts nicely
        run: |
          chmod a+x pack.sh
          ./pack.sh

      - name: Generate changelog
        run: |
          export FORGEJO_TOKEN=${{ secrets.FORGEJO_TOKEN }}
          ./changelog/tag.sh > changelog.md

      - name: Delete Previous Release
        run: |
          gh release delete "$FORGEJO_REF" --repo "$REPO" --cleanup-tag  -y
          sleep 5
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Eden ${{ env.FORGEJO_REF }}"
          tag_name: ${{ env.FORGEJO_REF }}
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          prerelease: false
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*