name: "[Auto] Build on create 'tag'"

on:
  repository_dispatch:
    types: [tag]

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    concurrency:
      group: tag-build
      cancel-in-progress: true
    uses: ./.github/workflows/build.yml
    with:
      build-type: 'Release'
      devel: false
      build-id: 'tag'
    secrets: inherit

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0

      - name: Load payload environment
        shell: bash
        run: |
          export FORGEJO_LENV=forgejo-env/forgejo.env
          . ./.ci/common/load-env.sh --load-payload-env

      - name: Set environment variables
        run: |
          echo "REPO=eden-emulator/Releases" >> $GITHUB_ENV
          echo "DEVEL=false" >> $GITHUB_ENV

          case "${{ env.FORGEJO_REF }}" in
            (*rc*|*alpha*|*beta*)
              echo "TRACK=beta" >> $GITHUB_ENV
              ;;
            (*)
              echo "TRACK=production" >> $GITHUB_ENV
              ;;
          esac

      - name: Package artifacts nicely
        run: |
          export ID=${FORGEJO_REF}
          ./pack.sh

      - name: Generate changelog(s)
        run: |
          ./.ci/changelog/generate.sh tag > changelog.md
          mkdir -p whatsnew
          echo "See the changelog here: https://github.com/eden-emulator/Releases/releases/tag/${{ env.FORGEJO_REF }}" > whatsnew/whatsnew-en-US

      # - uses: r0adkll/upload-google-play@v1.1.3
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.PLAY_CREDENTIALS }}
      #     packageName: dev.eden.eden_emulator
      #     track: ${{ env.TRACK }}
      #     releaseFiles: android-aab/*.aab
      #     whatsNewDirectory: whatsnew
      #     releaseName: ${{ env.FORGEJO_REF }}

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Eden ${{ env.FORGEJO_REF }}"
          tag_name: ${{ env.FORGEJO_REF }}
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          prerelease: false
          draft: true
          generate_release_notes: false
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*

      - name: Add release URL to summary
        run: |
          {
            echo "## Release Summary"
            echo ""
            echo "- View Release on GitHub: [${{ env.FORGEJO_REF }}](${{ steps.release.outputs.url }})"
            echo ""
          } > RELEASE_GITHUB_SUMMARY.md
          cat "$GITHUB_SUMMARY" > OLD_GITHUB_SUMMARY.md
          cat RELEASE_GITHUB_SUMMARY.md OLD_GITHUB_SUMMARY.md > "$GITHUB_SUMMARY"
