name: "[Manual] Workflow for Test"

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      devel:
        description: 'Development mode (disables update checker, adds nightly qualifier)'
        type: boolean
        default: true
      build-id:
        description: 'Identifier for workflows and caching'
        type: choice
        default: test
        options: 
          - test
          - master
      test-ref:
        description: 'Override (hash reference) commit for test build'
        type: string
        default: ''
      test-before:
        description: 'Override (hash reference)-1 commit for test build'
        type: string
        default: ''
env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  # TODO: Create a fake payload to ONLY test all workflows without building packages
  build:
    name: Build
    concurrency:
      group: test-build
      cancel-in-progress: true
    uses: ./.github/workflows/build.yml
    with:
      devel: true
      build-id: ${{ inputs.build-id }}
    secrets: inherit

  release:
    name: Test Release
    needs: [build]
    uses: ./.github/workflows/release.yml
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write
    with:
      devel: true
      build-id: ${{ inputs.build-id }}
    secrets: inherit
