name: "[Manual] Workflow PR"

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  # TODO: Create a fake payload to ONLY test all workflows without building packages
  build:
    name: Build
    concurrency:
      group: test-build
      cancel-in-progress: true
    uses: ./.github/workflows/build.yml
    with:
      build-id: 'test'
    secrets: inherit

  release:
    name: Test Release
    needs: [build]
    uses: ./.github/workflows/release.yml
    with:
      build-id: 'test'
    secrets: inherit
