name: "Windows"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true
      force_pgo:
        description: 'test PGO builds'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}

jobs:
  win-matrix:
    name: "Generate Windows compilers"
    runs-on: ubuntu-latest
    outputs:
      compiler: ${{ steps.set.outputs.compiler }}
    steps:
      - id: set
        run: |
          PGO='{"program": "clang", "target": "pgo"}'
          CLANG='{"program": "clang", "target": "standard"}'
          MSVC='{"program": "msvc", "target": "standard"}'

          if [ "${{ inputs.devel }}" != "true" ] || [ "${{ inputs.force_pgo }}" = "true" ]; then
            COMPILER="[${MSVC},${PGO}]"
          else
            COMPILER="[${MSVC}]"
          fi

          echo $COMPILER
          echo "compiler=${COMPILER}" >> $GITHUB_OUTPUT

  windows:
    name: "Windows ${{ matrix.os.arch }} ${{ matrix.compiler.program }} ${{ matrix.compiler.target }}"
    needs: [win-matrix]
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: windows-latest
            arch: amd64
          - runs-on: windows-11-arm
            arch: arm64
        compiler: ${{ fromJson(needs.win-matrix.outputs.compiler) }}

    env:
      QT_VERSION: 6.9.1
      TARGET: ${{ matrix.os.arch }}
      COMPILER: "${{ matrix.compiler.program }}"
      PGO_TARGET: "${{ matrix.compiler.target }}"
      ARCH: ${{ matrix.os.arch }}-${{ matrix.compiler.program }}-${{ matrix.compiler.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler.program }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
        with:
          version: ${{ env.QT_VERSION }}
          cache: 'true'

      - name: Load payload environment
        shell: bash
        run: |
          . ./.ci/fj/load-env.sh

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.os.arch }}

      - name: Install LLVM/Clang
        if: matrix.compiler.program == 'clang'
        uses: Vee99BR/install-llvm-action@v1
        with:
          version: "21.1.4"
          env: true

      - name: Check LLVM/Clang
        if: matrix.compiler.program == 'clang'
        shell: bash
        run: |
          echo "C:/Program Files/LLVM/bin" >> $GITHUB_PATH
          "C:/Program Files/LLVM/bin/clang-cl" --version

      - name: Install Vulkan SDK
        shell: powershell
        run: |
          ./.ci/windows/install-vulkan-sdk.ps1

      - name: Configure
        shell: bash
        run: |
          git config --global core.autocrlf off
          dos2unix .patch/boost/*
          .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        shell: bash
        run: cmake --build build

      - name: Package
        shell: bash
        run: ./.ci/windows/package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-${{ env.ARCH }}
          path: artifacts/*

